version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: martgreen-server-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - martgreen-network

networks:
  martgreen-network:
    driver: bridge
