version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: martgreen-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: martgreen_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - martgreen-network

  redis:
    image: redis:7-alpine
    container_name: martgreen-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - martgreen-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: martgreen-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/martgreen_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - martgreen-network
    command: npm run start:dev

volumes:
  postgres_data:
  redis_data:

networks:
  martgreen-network:
    driver: bridge
