name: Develop CI (Test & Lint Only)

on:
      push:
            branches: [develop]
            paths:
                  - "apps/server/**"
                  - "apps/web/**"
                  - ".github/workflows/develop-ci.yml"
      pull_request:
            branches: [develop]
            paths:
                  - "apps/server/**"
                  - "apps/web/**"
                  - ".github/workflows/develop-ci.yml"

jobs:
      server-ci:
            runs-on: ubuntu-latest
            if: contains(github.event.head_commit.modified, 'apps/server/') || contains(github.event.head_commit.added, 'apps/server/') || github.event_name == 'pull_request'

            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Setup Node.js
                    uses: actions/setup-node@v4
                    with:
                          node-version: "20"
                          cache: "npm"
                          cache-dependency-path: apps/server/package-lock.json

                  - name: Install dependencies
                    working-directory: apps/server
                    run: npm install

                  - name: Run linting
                    working-directory: apps/server
                    run: npm run lint

                  - name: Run tests
                    working-directory: apps/server
                    run: npm run test

                  - name: Build application (test only)
                    working-directory: apps/server
                    run: npm run build

      web-ci:
            runs-on: ubuntu-latest
            if: contains(github.event.head_commit.modified, 'apps/web/') || contains(github.event.head_commit.added, 'apps/web/') || github.event_name == 'pull_request'

            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Setup Node.js
                    uses: actions/setup-node@v4
                    with:
                          node-version: "20"
                          cache: "npm"
                          cache-dependency-path: apps/web/package-lock.json

                  - name: Install dependencies
                    working-directory: apps/web
                    run: npm install

                  - name: Run linting
                    working-directory: apps/web
                    run: npm run lint --if-present

                  - name: Run tests
                    working-directory: apps/web
                    run: npm run test --if-present

                  - name: Build application (test only)
                    working-directory: apps/web
                    run: npm run build
