name: Develop CI (Test & Lint Only)

on:
  push:
    branches: [develop]
    paths:
      - "apps/server/**"
      - "apps/web/**"
      - ".github/workflows/develop-ci.yml"
  pull_request:
    branches: [develop]
    paths:
      - "apps/server/**"
      - "apps/web/**"
      - ".github/workflows/develop-ci.yml"

jobs:
  server-ci:
    name: 🧠 Server (NestJS) CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: apps/server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --coverage

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: apps/server/coverage

      - name: Build (Verification)
        run: npm run build

  web-ci:
    name: 💻 Web (Nuxt/Vue) CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run Tests
        run: npm run test --if-present

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-coverage
          path: apps/web/coverage

      - name: Build (Verification)
        run: npm run build
